apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: ha-demo-db
spec:
    version: "10.2-v2"
    replicas: 2
    standbyMode: Hot
    storageType: Durable
    storage:
      storageClassName: "rook-ceph-block"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
    terminationPolicy: DoNotTerminate