apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-demo-storage
  labels:
    app: ha-demo-be
spec:
  storageClassName: rook-ceph-block
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5G